<?php
/**
 * PutApiV1LivechatRoomVisitorRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatOmnichannelApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnichannel
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatOmnichannelApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PutApiV1LivechatRoomVisitorRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PutApiV1LivechatRoomVisitorRequest
 * @package     RocketChatOmnichannelApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PutApiV1LivechatRoomVisitorRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PutApiV1LivechatRoomVisitorRequest"
     */
    public function testPutApiV1LivechatRoomVisitorRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rid"
     */
    public function testPropertyRid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "old_visitor_id"
     */
    public function testPropertyOldVisitorId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "new_visitor_id"
     */
    public function testPropertyNewVisitorId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
