<?php
/**
 * GetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatStatisticsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Statistics
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatStatisticsApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInner
 * @package     RocketChatStatisticsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInner"
     */
    public function testGetApiV1EngagementDashboardMessagesOrigin200ResponseOriginsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "t"
     */
    public function testPropertyT()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
