<?php
/**
 * GetApiV1EmojiCustomList200ResponseEmojisTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatContentManagementApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Content Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatContentManagementApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetApiV1EmojiCustomList200ResponseEmojisTest Class Doc Comment
 *
 * @category    Class
 * @description GetApiV1EmojiCustomList200ResponseEmojis
 * @package     RocketChatContentManagementApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetApiV1EmojiCustomList200ResponseEmojisTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetApiV1EmojiCustomList200ResponseEmojis"
     */
    public function testGetApiV1EmojiCustomList200ResponseEmojis()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "update"
     */
    public function testPropertyUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remove"
     */
    public function testPropertyRemove()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
