<?php
/**
 * LivechatUnitsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatOmnichannelApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnichannel
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RocketChatOmnichannelApi\Test\Api;

use \RocketChatOmnichannelApi\Configuration;
use \RocketChatOmnichannelApi\ApiException;
use \RocketChatOmnichannelApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LivechatUnitsApiTest Class Doc Comment
 *
 * @category Class
 * @package  RocketChatOmnichannelApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LivechatUnitsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteApiV1LivechatUnitsId
     *
     * Delete a Unit.
     *
     */
    public function testDeleteApiV1LivechatUnitsId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnits
     *
     * Get List of Units.
     *
     */
    public function testGetApiV1LivechatUnits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsGetOne
     *
     * Get One Unit.
     *
     */
    public function testGetApiV1LivechatUnitsGetOne()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsList
     *
     * List of Units.
     *
     */
    public function testGetApiV1LivechatUnitsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsMonitorsList
     *
     * List of Unit Monitors.
     *
     */
    public function testGetApiV1LivechatUnitsMonitorsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsUnitId
     *
     * Get a Unit.
     *
     */
    public function testGetApiV1LivechatUnitsUnitId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsUnitIdDepartments
     *
     * Get Departments by Unit ID.
     *
     */
    public function testGetApiV1LivechatUnitsUnitIdDepartments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsUnitIdDepartmentsAvailable
     *
     * Get Available Departments by Unit Id.
     *
     */
    public function testGetApiV1LivechatUnitsUnitIdDepartmentsAvailable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiV1LivechatUnitsUnitIdMonitors
     *
     * Get List of Unit Monitors.
     *
     */
    public function testGetApiV1LivechatUnitsUnitIdMonitors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postApiV1LivechatUnits
     *
     * Create Unit.
     *
     */
    public function testPostApiV1LivechatUnits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postApiV1LivechatUnitsId
     *
     * Update Unit.
     *
     */
    public function testPostApiV1LivechatUnitsId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
