<?php
/**
 * GetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatSettingsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Settings
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatSettingsApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformationTest Class Doc Comment
 *
 * @category    Class
 * @description GetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformation
 * @package     RocketChatSettingsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformation"
     */
    public function testGetApiV1InstancesGet200ResponseInstancesInnerInstanceRecordExtraInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tcp_port"
     */
    public function testPropertyTcpPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "node_version"
     */
    public function testPropertyNodeVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "conns"
     */
    public function testPropertyConns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
