<?php
/**
 * PostApiV1StartImportRequestInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatSettingsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Settings
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatSettingsApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostApiV1StartImportRequestInputTest Class Doc Comment
 *
 * @category    Class
 * @description The input object contains two arrays: &#x60;users&#x60; and &#x60;channels&#x60;.
 * @package     RocketChatSettingsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostApiV1StartImportRequestInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostApiV1StartImportRequestInput"
     */
    public function testPostApiV1StartImportRequestInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
