<?php
/**
 * GetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatMiscellaneousApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Miscellaneous
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatMiscellaneousApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInner
 * @package     RocketChatMiscellaneousApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInner"
     */
    public function testGetApiV1LicensesInfo200ResponseLicenseLicenseValidationServerUrlsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
