<?php
/**
 * GetApiV1LicensesInfo200ResponseLicensePreventedActionsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatMiscellaneousApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Miscellaneous
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RocketChatMiscellaneousApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetApiV1LicensesInfo200ResponseLicensePreventedActionsTest Class Doc Comment
 *
 * @category    Class
 * @description GetApiV1LicensesInfo200ResponseLicensePreventedActions
 * @package     RocketChatMiscellaneousApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetApiV1LicensesInfo200ResponseLicensePreventedActionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetApiV1LicensesInfo200ResponseLicensePreventedActions"
     */
    public function testGetApiV1LicensesInfo200ResponseLicensePreventedActions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "active_users"
     */
    public function testPropertyActiveUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guest_users"
     */
    public function testPropertyGuestUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rooms_per_guest"
     */
    public function testPropertyRoomsPerGuest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "private_apps"
     */
    public function testPropertyPrivateApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "marketplace_apps"
     */
    public function testPropertyMarketplaceApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monthly_active_contacts"
     */
    public function testPropertyMonthlyActiveContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
