<?php
/**
 * CustomUserStatusApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RocketChatContentManagementApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Content Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RocketChatContentManagementApi\Test\Api;

use \RocketChatContentManagementApi\Configuration;
use \RocketChatContentManagementApi\ApiException;
use \RocketChatContentManagementApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomUserStatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  RocketChatContentManagementApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomUserStatusApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getApiV1CustomUserStatusList
     *
     * List Custom User Status.
     *
     */
    public function testGetApiV1CustomUserStatusList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postApiV1CustomUserStatusCreate
     *
     * Create Custom Status.
     *
     */
    public function testPostApiV1CustomUserStatusCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postApiV1CustomUserStatusDelete
     *
     * Delete Custom User Status.
     *
     */
    public function testPostApiV1CustomUserStatusDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postApiV1CustomUserStatusUpdate
     *
     * Update Custom Status.
     *
     */
    public function testPostApiV1CustomUserStatusUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
