name: OpenApi Client Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  authentication:
    name: Build API Clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Authentication API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/authentication.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\AuthenticationApi -o ./AuthenticationApi
      - name: Generate Content Management API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/content-management.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\ContentManagementApi -o ./ContentManagementApi
      - name: Generate Marketplace Apps API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/marketplace-apps.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\MarketplaceAppsApi -o ./MarketplaceAppsApi
      - name: Generate Messaging API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/messaging.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\MessagingApi -o ./MessagingApi
      - name: Generate Miscellaneous API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/miscellaneous.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\MiscellaneousApi -o ./MiscellaneousApi
      - name: Generate Notifications API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/notifications.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\NotificationsApi -o ./NotificationsApi
      - name: Generate Omnichannel API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/omnichannel.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\OmnichannelApi -o ./OmnichannelApi
      - name: Generate Rooms API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/rooms.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\RoomsApi -o ./RoomsApi
      - name: Generate Settings API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/settings.yaml
          command-args: --skip-validate-spec --additional-properties invokerPackage=WebMI\RocketChatApiClient\SettingsApi -o ./SettingsApi
      - name: Generate Statistics API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/statistics.yaml
          command-args: --additional-properties invokerPackage=WebMI\RocketChatApiClient\StatisticsApi -o ./StatisticsApi
      - name: Generate User Management API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/refs/heads/main/user-management.yaml
          command-args: --skip-validate-spec --additional-properties invokerPackage=WebMI\RocketChatApiClient\UserManagementApi -o ./UserManagementApi
      - name: Commit APIs
        run: |
          git add .
          git config --global user.name 'Web-MI'
          git config --global user.email 'info@web-mi.de'
          git commit -am "Updated APIs"
          git push
